add_newline = true
format = "$all"

[directory]
truncation_length = 0
truncate_to_repo = false

[username]
style_user = "green bold"

[aws]
disabled = true

[gcloud]
disabled = true

[git_status]
format = '([\[ $all_status$ahead_behind\]]($style) )'
style = "white bold"
modified = '[!$count ](yellow bold)'
staged = '[+$count ](green bold)'
conflicted = '[=${count} ](red bold)'
ahead = '⇡${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
behind = '⇣${count} '
stashed = '\$${count} '
